[package]
name = "ksu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
libc = "0.2.178"
nix = { version = "0.30.1", default-features = false, features = ["ioctl"] }
rustix = { version = "1.1.3", features = ["fs"] }
